In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import json
import os
import sklearn as sk

In [14]:
from sklearn.model_selection import StratifiedKFold
X_aug = np.load('../data/data_aug_2000.npy')
y_aug = pd.read_csv('../data/labels_aug_2000.csv', delimiter=',', index_col=0).to_numpy()
print(y_aug[-1])
labels_aug = []

for i in range(len(y_aug)):
    # print(y_aug[i])
    if 1 in y_aug[i]:
        k = np.where(y_aug[i] == 1)[0][0]
        labels_aug.append(k)
    else:
        labels_aug.append(7)

labels_aug = np.array(labels_aug)
ind = np.where(labels_aug == 7)
print(ind)


kf = StratifiedKFold(n_splits=12, shuffle=True, random_state=42)




[0 1 0 0 0 0]
(array([ 3688,  8072,  8769, 10340]),)


In [15]:
cross_ind = []

for train_index, val_index in kf.split(X = X_aug, y = labels_aug):
    # train_data, val_data = X_aug[train_index], X_aug[val_index]
    # train_labels, val_labels = y_aug[train_index], y_aug[val_index]
    cross_ind.append(val_index)

cross_ind = np.array(cross_ind)
print(cross_ind)

[array([    4,    13,    26, ..., 11942, 11945, 11986])
 array([    3,     8,     9, ..., 11981, 11987, 11990])
 array([    7,    21,    31, ..., 11965, 11967, 12001])
 array([   11,    20,    41, ..., 11956, 11968, 11972])
 array([   28,    43,    53,    75,   106,   115,   118,   123,   124,
          136,   140,   150,   152,   174,   180,   191,   222,   232,
          260,   275,   298,   307,   308,   320,   336,   349,   358,
          362,   396,   414,   415,   433,   448,   492,   506,   509,
          513,   516,   524,   530,   541,   557,   573,   580,   592,
          593,   620,   621,   633,   663,   687,   694,   710,   726,
          730,   735,   754,   758,   789,   805,   843,   849,   856,
          862,   864,   873,   888,   894,   903,   919,   922,   927,
          941,   944,   950,   957,   965,   978,   988,   994,  1002,
         1003,  1010,  1016,  1031,  1041,  1087,  1091,  1094,  1101,
         1104,  1123,  1131,  1160,  1167,  1186,  1196,  1197,  1

/home/maxm/conda/envs/default/lib/python3.10/site-packages/sklearn/model_selection/_split.py:776: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=12.
  warnings.warn(
/tmp/ipykernel_3394/3001742484.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  cross_ind = np.array(cross_ind)


In [16]:
print(len(X_aug[cross_ind[0]]))
labels_1_6 = y_aug[cross_ind[0]]
print(labels_1_6.sum(axis = 0))

1001
[166 167 166 167 167 167]


In [17]:
np.save('../data/cross_val_6fold_2000.npy', cross_ind)

In [18]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold

# Load data
X = np.load('../data/data_aug_2000.npy')
y = pd.read_csv('../data/labels_aug_2000.csv', delimiter=',', index_col=0).to_numpy()

# Generate labels
labels_aug = []
for i in range(len(y)):
    if 1 in y[i]:
        k = np.argmax(y[i])
        labels_aug.append(k)
    else:
        labels_aug.append(7)

# Create KFold object
kf = KFold(n_splits=10)

# Ensure the directory exists
output_dir = "../data/6_fold/"
os.makedirs(output_dir, exist_ok=True)

# Split into 10 folds and save
for i, (train_index, test_index) in enumerate(kf.split(X, labels_aug)):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    val_size = int(0.15 * X_train.shape[0])
    X_val = X_train[:val_size]
    y_val = y_train[:val_size]
    X_train = X_train[val_size:]
    y_train = y_train[val_size:]

    np.save(os.path.join(output_dir, f"X_train_fold{i}.npy"), X_train)
    np.save(os.path.join(output_dir, f"y_train_fold{i}.npy"), y_train)
    np.save(os.path.join(output_dir, f"X_val_fold{i}.npy"), X_val)
    np.save(os.path.join(output_dir, f"y_val_fold{i}.npy"), y_val)
    np.save(os.path.join(output_dir, f"X_test_fold{i}.npy"), X_test)
    np.save(os.path.join(output_dir, f"y_test_fold{i}.npy"), y_test)

print("Data split into 10 folds")

KeyboardInterrupt: 